import type { OptionDraftRow, OptionSetDraft } from "../models/optionSetModels";

export function serializeDraftToCode(draft: OptionSetDraft): string {
  return JSON.stringify(draft, null, 4);
}

export function parseCodeToDraft(code: string): OptionSetDraft {
  const parsed = JSON.parse(code) as OptionSetDraft;

  if (typeof parsed !== "object" || parsed === null) {
    throw new Error("Code payload must be a JSON object.");
  }
  if (!Array.isArray(parsed.rows)) {
    throw new Error("Code payload must contain a \"rows\" array.");
  }
  for (let i = 0; i < parsed.rows.length; i++) {
    const row = parsed.rows[i];
    if (typeof row.rowId !== "string") {
      throw new Error(`Row at index ${i} is missing a string "rowId".`);
    }
    if (!Array.isArray(row.labels)) {
      throw new Error(`Row at index ${i} (rowId: "${row.rowId}") is missing a "labels" array.`);
    }
  }

  return parsed;
}

function toEnumMemberName(label: string): string {
    const cleaned = label.trim().replace(/[^a-zA-Z0-9]+/g, " ").trim();
    const pascal = cleaned
        .split(" ")
        .filter(Boolean)
        .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
        .join("");
    if (!pascal) return "Option";
    return /^\d/.test(pascal) ? `_${pascal}` : pascal;
}

function toPascalCase(text: string): string {
    return text
        .trim()
        .replace(/[^a-zA-Z0-9]+/g, " ")
        .split(" ")
        .filter(Boolean)
        .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
        .join("");
}

function getDefaultLabel(row: OptionDraftRow, defaultLanguageCode: number): string {
    return (
        row.labels.find((l) => l.languageCode === defaultLanguageCode)?.label ??
        row.labels[0]?.label ??
        ""
    );
}

export function serializeDraftToTypeScript(draft: OptionSetDraft): string {
    const enumName = toPascalCase(draft.displayName || draft.optionSetSchemaName || "OptionSet");
    const lines: string[] = [];
    lines.push(`// Generated by OptionSet Manager`);
    lines.push(`// Schema: ${draft.optionSetSchemaName}`);
    lines.push(``);
    lines.push(`export enum ${enumName} {`);
    for (const row of draft.rows) {
        const label = getDefaultLabel(row, draft.defaultLanguageCode);
        const memberName = toEnumMemberName(label || `Option${row.optionValue ?? ""}`);
        const value = row.optionValue ?? "/* value not set */";
        lines.push(`    ${memberName} = ${value},`);
    }
    lines.push(`}`);
    return lines.join("\n");
}

export function serializeDraftToJavaScript(draft: OptionSetDraft): string {
    const constName = toPascalCase(draft.displayName || draft.optionSetSchemaName || "OptionSet");
    const lines: string[] = [];
    lines.push(`// Generated by OptionSet Manager`);
    lines.push(`// Schema: ${draft.optionSetSchemaName}`);
    lines.push(``);
    lines.push(`/** @readonly @enum {number} */`);
    lines.push(`export const ${constName} = Object.freeze({`);
    for (const row of draft.rows) {
        const label = getDefaultLabel(row, draft.defaultLanguageCode);
        const memberName = toEnumMemberName(label || `Option${row.optionValue ?? ""}`);
        const value = row.optionValue ?? "null /* value not set */";
        lines.push(`    ${memberName}: ${value},`);
    }
    lines.push(`});`);
    return lines.join("\n");
}

export function serializeDraftToCSharp(draft: OptionSetDraft): string {
    const enumName = toPascalCase(draft.displayName || draft.optionSetSchemaName || "OptionSet");
    const lines: string[] = [];
    lines.push(`// Generated by OptionSet Manager`);
    lines.push(`// Schema: ${draft.optionSetSchemaName}`);
    lines.push(``);
    lines.push(`public enum ${enumName}`);
    lines.push(`{`);
    for (const row of draft.rows) {
        const label = getDefaultLabel(row, draft.defaultLanguageCode);
        const memberName = toEnumMemberName(label || `Option${row.optionValue ?? ""}`);
        const value = row.optionValue ?? "/* value not set */";
        lines.push(`    ${memberName} = ${value},`);
    }
    lines.push(`}`);
    return lines.join("\n");
}

export function serializeDraftToCsv(draft: OptionSetDraft): string {
    const rows: string[] = [];
    rows.push("Value,Label,Description");
    for (const row of draft.rows) {
        const label = getDefaultLabel(row, draft.defaultLanguageCode);
        const desc = row.labels.find((l) => l.languageCode === draft.defaultLanguageCode)?.description ?? "";
        const value = row.optionValue ?? "";
        const escapedLabel = `"${label.replace(/"/g, '""')}"`;
        const escapedDesc = `"${desc.replace(/"/g, '""')}"`;
        rows.push(`${value},${escapedLabel},${escapedDesc}`);
    }
    return rows.join("\n");
}
