/**
 * Settings Models
 *
 * Type definitions for application settings.
 */

export interface OptionSetManagerSettings {
  /**
   * Auto-generate code when builder changes (with debounce)
   */
  autoGenerateCode: boolean;

  /**
   * Auto-generate code debounce delay in milliseconds
   */
  autoGenerateDebounceMs: number;

  /**
   * Default language code for option set labels
   */
  defaultLanguageCode: number;

  /**
   * Sort language dropdown by code (numeric) instead of alphabetically
   */
  sortLanguagesByCode: boolean;

  /**
   * Which language codes appear in the Add Language dropdown
   */
  visibleLanguageCodes: number[];

  /**
   * Show system (non-custom) option sets in the Global option set list
   */
  showSystemOptionSets: boolean;
}

export const DEFAULT_SETTINGS: OptionSetManagerSettings = {
  autoGenerateCode: true,
  autoGenerateDebounceMs: 500,
  defaultLanguageCode: 1033,
  sortLanguagesByCode: false,
  visibleLanguageCodes: [1033, 1036, 1031, 1034, 1040, 1043, 1046, 1041, 2052, 1042],
  showSystemOptionSets: false,
};
