import { DEFAULT_LANGUAGE_CODE, DEFAULT_SORT_LANGUAGES_BY_CODE, DEFAULT_VISIBLE_LANGUAGE_CODES } from "../components/languages/languageConfig";

/**
 * Settings Models
 *
 * Type definitions for application settings.
 */

/** Controls which language is used as the primary row in the builder. */
export type PrimaryLanguageMode = "english" | "environmentDefault";

export interface OptionSetManagerSettings {
    /** Auto-generate code when builder changes (with debounce) */
    autoGenerateCode: boolean;

    /** Auto-generate code debounce delay in milliseconds */
    autoGenerateDebounceMs: number;

    /**
     * Controls the primary label language.
     * "english" pins 1033; "environmentDefault" uses the environment base language.
     */
    primaryLanguageMode: PrimaryLanguageMode;

    /** When primaryLanguageMode is "environmentDefault", also add 1033 as a sub-row automatically. */
    autoAddEnglishSubrow: boolean;

    /** Default language code for option set labels (derived from primaryLanguageMode at runtime). */
    defaultLanguageCode: number;

    /** Sort language dropdown by code (numeric) instead of alphabetically. */
    sortLanguagesByCode: boolean;

    /** Which language codes appear in the Add Language dropdown. */
    visibleLanguageCodes: number[];

    /** Show system (non-custom) option sets in the Global option set list. */
    showSystemOptionSets: boolean;

    /** Warn on rows that have empty translation labels. */
    validateBlankTranslationRows: boolean;

    /** Include all environment languages as sub-rows when a row is expanded. */
    autoAddAllLanguages: boolean;

    /** If true, show all languages in dropdowns regardless of environment. */
    showAllLanguagesInDropdowns: boolean;

    // ── Table Preferences ──

    /** Hide the gear/advanced-properties icon on individual rows. */
    hideRowAdvancedProperties: boolean;

    /** Auto-expand language sub-rows when a new row is added. */
    autoExpandSubrowsOnAdd: boolean;

    /** Auto-add all environment languages when a new row is added. */
    autoAddAllLanguagesOnAdd: boolean;
}

export const DEFAULT_SETTINGS: OptionSetManagerSettings = {
    autoGenerateCode: true,
    autoGenerateDebounceMs: 500,
    primaryLanguageMode: "english",
    autoAddEnglishSubrow: false,
    defaultLanguageCode: DEFAULT_LANGUAGE_CODE,
    sortLanguagesByCode: DEFAULT_SORT_LANGUAGES_BY_CODE,
    visibleLanguageCodes: [...DEFAULT_VISIBLE_LANGUAGE_CODES],
    showSystemOptionSets: true,
    validateBlankTranslationRows: true,
    autoAddAllLanguages: false,
    showAllLanguagesInDropdowns: false,
    hideRowAdvancedProperties: false,
    autoExpandSubrowsOnAdd: false,
    autoAddAllLanguagesOnAdd: false,
};
