/**
 * Settings Panel Component
 *
 * Drawer-style settings panel for OptionSet Manager configuration.
 */

import { Button, Checkbox, Divider, Drawer, DrawerBody, DrawerHeader, DrawerHeaderTitle, Dropdown, Input, Label, makeStyles, Option, tokens } from "@fluentui/react-components";
import { DismissRegular } from "@fluentui/react-icons";
import { useState } from "react";
import { LANGUAGE_CONFIGS } from "../languages/languageConfig";
import type { OptionSetManagerSettings } from "../../models/settingsModels";
import { ConfirmDialog } from "../common";
import { LanguageCodeDropdown } from "../common/LanguageCodeDropdown";

const useStyles = makeStyles({
    body: {
        display: "flex",
        flexDirection: "column",
        gap: tokens.spacingVerticalL,
        padding: tokens.spacingVerticalL,
    },
    group: {
        display: "flex",
        flexDirection: "column",
        gap: tokens.spacingVerticalM,
    },
    groupTitle: {
        fontSize: tokens.fontSizeBase200,
        fontWeight: tokens.fontWeightSemibold,
        color: tokens.colorNeutralForeground3,
        textTransform: "uppercase",
        letterSpacing: "0.05em",
    },
    section: {
        display: "flex",
        flexDirection: "column",
        gap: tokens.spacingVerticalXS,
    },
    description: {
        fontSize: tokens.fontSizeBase200,
        color: tokens.colorNeutralForeground2,
        margin: "0",
    },
    checkboxDescription: {
        fontSize: tokens.fontSizeBase200,
        color: tokens.colorNeutralForeground2,
        margin: "0",
        marginLeft: `calc(${tokens.spacingHorizontalS} + 20px)`,
    },
    indented: {
        paddingLeft: `calc(${tokens.spacingHorizontalS} + 20px)`,
        display: "flex",
        flexDirection: "column",
        gap: tokens.spacingVerticalXS,
    },
    inputFull: {
        width: "100%",
    },
    footer: {
        display: "flex",
        gap: tokens.spacingHorizontalM,
        paddingTop: tokens.spacingVerticalL,
        borderTop: `${tokens.strokeWidthThin} solid ${tokens.colorNeutralStroke1}`,
        marginTop: "auto",
    },
    footerButton: {
        flex: 1,
    },
});

interface SettingsPanelProps {
    isOpen: boolean;
    onClose: () => void;
    settings: OptionSetManagerSettings;
    onUpdateSettings: (partial: Partial<OptionSetManagerSettings>) => Promise<void>;
    onResetSettings: () => Promise<void>;
}

export function SettingsPanel({ isOpen, onClose, settings, onUpdateSettings, onResetSettings }: SettingsPanelProps): JSX.Element {
    const styles = useStyles();
    const [resetConfirmOpen, setResetConfirmOpen] = useState(false);

    const handleAutoGenerateChange = async (checked: boolean): Promise<void> => {
        await onUpdateSettings({ autoGenerateCode: checked });
    };

    const handleDebounceChange = async (value: number): Promise<void> => {
        await onUpdateSettings({ autoGenerateDebounceMs: value });
    };

    const handleDefaultLanguageChange = async (value: number): Promise<void> => {
        await onUpdateSettings({ defaultLanguageCode: value });
    };

    const handleSortLanguagesChange = async (sortByCode: boolean): Promise<void> => {
        await onUpdateSettings({ sortLanguagesByCode: sortByCode });
    };

    const handleVisibleLanguagesChange = async (codes: number[]): Promise<void> => {
        await onUpdateSettings({ visibleLanguageCodes: codes });
    };

    const handleShowSystemOptionSetsChange = async (checked: boolean): Promise<void> => {
        await onUpdateSettings({ showSystemOptionSets: checked });
    };

    const handleReset = (): void => {
        setResetConfirmOpen(true);
    };

    return (
        <>
            <Drawer type="overlay" position="end" open={isOpen} onOpenChange={(_, data) => !data.open && onClose()} size="medium">
                <DrawerHeader>
                    <DrawerHeaderTitle action={<Button appearance="subtle" icon={<DismissRegular />} onClick={onClose} aria-label="Close settings" />}>Settings</DrawerHeaderTitle>
                </DrawerHeader>
                <DrawerBody className={styles.body}>
                    {/* ── Language ── */}
                    <div className={styles.group}>
                        <span className={styles.groupTitle}>Language</span>

                        <div className={styles.section}>
                            <Label htmlFor="defaultLanguageCode" weight="semibold">
                                Default Language
                            </Label>
                            <p className={styles.description}>The primary LCID used for option set labels (e.g., 1033 for English).</p>
                            <LanguageCodeDropdown value={settings.defaultLanguageCode} onChange={handleDefaultLanguageChange} sortByCode={settings.sortLanguagesByCode} />
                        </div>

                        <div className={styles.section}>
                            <Label weight="semibold">Languages in Editor</Label>
                            <p className={styles.description}>Which languages appear in the Add Language dropdown in the builder.</p>
                            <Dropdown
                                multiselect
                                value={LANGUAGE_CONFIGS.filter((l) => settings.visibleLanguageCodes.includes(l.code))
                                    .map((l) => l.name)
                                    .join(", ")}
                                selectedOptions={settings.visibleLanguageCodes.map(String)}
                                onOptionSelect={(_, data) => {
                                    const selected = (data.selectedOptions ?? []).map(Number);
                                    void handleVisibleLanguagesChange(selected);
                                }}
                            >
                                {LANGUAGE_CONFIGS.map((lang) => (
                                    <Option key={lang.code} value={String(lang.code)} text={`${lang.emoji} ${lang.name}`}>
                                        {lang.emoji} {lang.name} ({lang.code})
                                    </Option>
                                ))}
                            </Dropdown>
                        </div>

                        <div className={styles.section}>
                            <Label weight="semibold">Sort Order</Label>
                            <Dropdown
                                value={settings.sortLanguagesByCode ? "By Code (1033, 1036, …)" : "Alphabetical (A–Z)"}
                                selectedOptions={[settings.sortLanguagesByCode ? "code" : "alphabetical"]}
                                onOptionSelect={(_, data) => handleSortLanguagesChange(data.optionValue === "code")}
                            >
                                <Option value="alphabetical" text="Alphabetical (A–Z)">
                                    Alphabetical (A–Z)
                                </Option>
                                <Option value="code" text="By Code (1033, 1036, …)">
                                    By Code (1033, 1036, …)
                                </Option>
                            </Dropdown>
                        </div>
                    </div>

                    <Divider />

                    {/* ── Entity Browsing ── */}
                    <div className={styles.group}>
                        <span className={styles.groupTitle}>Entity Browsing</span>

                        <div className={styles.section}>
                            <Checkbox checked={settings.showSystemOptionSets} onChange={(_, data) => handleShowSystemOptionSetsChange(!!data.checked)} label="Show System Option Sets" />
                            <p className={styles.checkboxDescription}>Include read-only system option sets in the Global option set list</p>
                        </div>
                    </div>

                    <Divider />

                    {/* ── Code Generation ── */}
                    <div className={styles.group}>
                        <span className={styles.groupTitle}>Code Generation</span>

                        <div className={styles.section}>
                            <Checkbox checked={settings.autoGenerateCode} onChange={(_, data) => handleAutoGenerateChange(!!data.checked)} label="Auto-Generate Code" />
                            <p className={styles.checkboxDescription}>Regenerate the Code tab automatically when the builder changes</p>
                        </div>

                        {settings.autoGenerateCode && (
                            <div className={styles.indented}>
                                <Label htmlFor="debounceDelay" weight="semibold">
                                    Debounce Delay (ms)
                                </Label>
                                <Input
                                    id="debounceDelay"
                                    type="number"
                                    min={100}
                                    max={5000}
                                    step={100}
                                    value={settings.autoGenerateDebounceMs.toString()}
                                    onChange={(_, data) => handleDebounceChange(parseInt(data.value, 10))}
                                    className={styles.inputFull}
                                />
                            </div>
                        )}
                    </div>

                    {/* Footer Actions */}
                    <div className={styles.footer}>
                        <Button appearance="secondary" onClick={handleReset} className={styles.footerButton}>
                            Reset to Defaults
                        </Button>
                        <Button appearance="primary" onClick={onClose} className={styles.footerButton}>
                            Close
                        </Button>
                    </div>
                </DrawerBody>
            </Drawer>

            <ConfirmDialog
                open={resetConfirmOpen}
                title="Reset Settings — OptionSet Manager"
                message="This will reset all OptionSet Manager settings to defaults. This cannot be undone."
                confirmLabel="Reset"
                confirmIntent="danger"
                cancelLabel="Cancel"
                onConfirm={async () => {
                    await onResetSettings();
                    setResetConfirmOpen(false);
                }}
                onCancel={() => setResetConfirmOpen(false)}
            />
        </>
    );
}
